name: game_selling_app
description: "Game Selling App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Services
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.10

  # Google Login
  google_sign_in: ^6.2.2

  # Networking
  http: ^1.2.2

  # UI/UX
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  hugeicons: ^0.0.9
  cached_network_image: ^3.4.1

  # State Management & Utils
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2

  # AI Support
  flutter_gemini: ^3.0.0

  # Enviroment
  flutter_dotenv: ^5.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  # Optional: If anh muốn dùng custom fonts sau
  # fonts:
  #   - family: GameFont
  #     fonts:
  #       - asset: assets/fonts/GameFont-Regular.ttf
  #       - asset: assets/fonts/GameFont-Bold.ttf
  #         weight: 700
