// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNB8DxKNqiV2tbg6lVb_NClSSX0v9A9kU',
    appId: '1:797791806867:web:82d666bd75de3235da7466',
    messagingSenderId: '797791806867',
    projectId: 'gamesellingapp-f26b7',
    authDomain: 'gamesellingapp-f26b7.firebaseapp.com',
    storageBucket: 'gamesellingapp-f26b7.firebasestorage.app',
    measurementId: 'G-N1Y490PQHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMeRsTYzjsNXkX1F9BL0hmborua6M0N0g',
    appId: '1:797791806867:android:5d46a8fd9251e28cda7466',
    messagingSenderId: '797791806867',
    projectId: 'gamesellingapp-f26b7',
    storageBucket: 'gamesellingapp-f26b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoeQgGibM1dEnvG5pNAwomBc2aSSgculw',
    appId: '1:797791806867:ios:1f617dad0b4a25b6da7466',
    messagingSenderId: '797791806867',
    projectId: 'gamesellingapp-f26b7',
    storageBucket: 'gamesellingapp-f26b7.firebasestorage.app',
    iosClientId:
        '797791806867-4nvm75as27ea66s5ab1aofjom90o3pbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoeQgGibM1dEnvG5pNAwomBc2aSSgculw',
    appId: '1:797791806867:ios:1f617dad0b4a25b6da7466',
    messagingSenderId: '797791806867',
    projectId: 'gamesellingapp-f26b7',
    storageBucket: 'gamesellingapp-f26b7.firebasestorage.app',
    iosClientId:
        '797791806867-4nvm75as27ea66s5ab1aofjom90o3pbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNB8DxKNqiV2tbg6lVb_NClSSX0v9A9kU',
    appId: '1:797791806867:web:fa890e76f2b8ae46da7466',
    messagingSenderId: '797791806867',
    projectId: 'gamesellingapp-f26b7',
    authDomain: 'gamesellingapp-f26b7.firebaseapp.com',
    storageBucket: 'gamesellingapp-f26b7.firebasestorage.app',
    measurementId: 'G-EK1475Q74J',
  );
}
